### PR TITLE
NameOnCard field is added to pass Credit Card Holder name on transaction

### PR DESCRIPTION
**Pull request by babuhaman**
Additional 'NameOnCard' field (optional) will enable the Credit Card Holder name on transaction.

### CODE REVIEW

**Comment by babuhaman** [comment]
I've just noticed an issue #19 is already created for this.

**Comment by hash-bang** [comment]
Thanks for that. Merged.

**Comment by babuhaman** [comment]
@hash-bang thanks for merging this PR. Are you planning to push it to the composer package as well?

**Comment by hash-bang** [comment]
Ah sorry. I keep forgetting I have to do a version release to keep Composer happy.
Should be upgradable when composer gets around to detecting the version bump.

**Pull request merged**
